os: osx 
osx_image: xcode10.2
language: bash

before_cache:
  - brew cleanup
  
 cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - whoami
  - echo "Start of pipeline"
  - HOMEBREW_NO_AUTO_UPDATE=1

script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh

after script:
  - echo "End of pipeline"
